### ISSUE TITLE
simulation revenu de base

### ISSUE THREAD

**Issue by revolunet** [openfisca/openfisca-web-site#43]
Bonjour,

Pour info je n'arrive pas à accéder aux simulations sur http://ui-test.openfisca.fr/
Quand je séletcionne "reforme des cotisations pour revenu de base" j'ai les erreurs suivantes :
![capture d ecran 2015-02-27 a 01 39 55](https://cloud.githubusercontent.com/assets/124937/6405253/90fae1cc-be21-11e4-9ffa-b5f1c194a75c.png)

Paramètres envoyés en POST à "simulate" :
```
{"base_reforms":["inversion_revenus"],"scenarios":[{"period":{"start":2013,"unit":"year"},"test_case":{"familles":[{"id":"25e286be-082e-4fea-a8d8-85bf2f5801c1","parents":["2ff453d5-7c5d-4163-a42f-a40492713198"],"nom_famille":"1"}],"foyers_fiscaux":[{"id":"564400fc-bb7b-493d-967e-5f042b947ce8","declarants":["2ff453d5-7c5d-4163-a42f-a40492713198"],"nom_foyer_fiscal":"1"}],"menages":[{"id":"0c7b2836-0c89-4309-a46e-05b3d8638c34","personne_de_reference":"2ff453d5-7c5d-4163-a42f-a40492713198","nom_menage":"1"}],"individus":[{"id":"2ff453d5-7c5d-4163-a42f-a40492713198","nom_individu":"Personne 1"}]}}],"reforms":["revenu_de_base_cotisations"]}
```

hope this helps

**Comment by cbenz** [comment]
Merci pour ton retour :smiley: 

Je suis désolé mais en ce moment, sur la plateforme de test (http://ui-test.openfisca.fr/ et http://api-test.openfisca.fr/), nous sommes en plein chantier sur les formules de calcul ce qui provoque des erreurs comme celle-ci.

Malheureusement les versions plus anciennes de l'application, sur la plateforme de production (http://ui.openfisca.fr/ et http://api.openfisca.fr/), ne fonctionnent pas avec les réformes du revenu de base.

Je pense qu'il faudra encore une à deux semaines pour sortir de ce chantier.

**Comment by revolunet** [comment]
ha ok merci bon courage! j'ai hate de voir ca :)
