### ISSUE TITLE
Installation requirement : biryani ?

### ISSUE THREAD

**Issue by adrienpacifico** [openfisca/openfisca-web-site#44]
Bonjour,

Il n'est pas indiqué ni donné de lien github pour biryani dans la doc d'install : http://www.openfisca.fr/documentation/installation

Cordialement,
Adrien
@cbenz

**Comment by benjello** [comment]
Biryani dispose d'un paquet accessible par pip. Et  il est en dépendance de
core et france (
https://github.com/openfisca/openfisca-core/blob/master/setup.py et
https://github.com/openfisca/openfisca-france/blob/master/setup.py) donc
l'installation des paquets après clonage par pip install --editable . --user
