### ISSUE TITLE
404 depuis la page Identité visuelle de beta.gouv.fr

### ISSUE THREAD

**Issue by guillett** [openfisca/openfisca-web-site#55]
Bonjour,

Sur la page Identite-visuelle du wiki de beta.gouv.fr il y a une section sur [Openfisca](https://github.com/sgmap/beta.gouv.fr/wiki/Identite-visuelle#logo-openfisca).

Dans la section, il y a une référence à @cbenz et le lien de de [hotlink](http://www.openfisca.fr/hotlinks/) est cassé.

JSYK.

**Comment by MattiSG** [comment]
[Corrigé](https://github.com/sgmap/beta.gouv.fr/wiki/Identite-visuelle/_compare/5f4eafa0b538275a3c2815e865c693ac63cfea2b...0bf409bee413cb33a96ffc5519950d7b7d8f2250) et [documenté](https://github.com/openfisca/openfisca-web-site/commit/c5431a3fb19a7dd39df309f6bb5ade1e3e0c977d), merci !  🙂
