### ISSUE TITLE
Determine what should be on fr.openfisca.org

### ISSUE THREAD

**Issue by fpagnoux** [openfisca/openfisca-web-site#56]
A lot of content on openfisca.fr is outdated or broken.

We will move the French OpenFisca website to `fr.openfisca.org`. 

Two suggestions : 

1. Move the current content of `openfisca.fr`, and removing any outdated content.
2. Build a small website from scratch, cherry picking only a few elements from `openfisca.fr`

A consensus  must be reached on this topic.

**Comment by fpagnoux** [comment]
First ideas :

- Highlight the partners
- Highliths reuses
- Present the UI as just a reuse, and not anything official
- Remove tweets
- Remove caroussel
- Remove all dead links, or stuff that don't work
- Remove the news
- Remove calculette impôts
- Replace "Etat du code source"  by "Status", which would link to status.openfisca.fr

**Comment by sandcha** [comment]
@benjello @guillett @cbenz Between the two suggestions described above, what would you prefer?

Moving the current `openfisca.fr` and cleaning its content (suggestion 1) means keeping its style or some of it.

Building `fr.openfisca.org` from scratch (suggestion 2) means using a similar style for `fr.openfisca.org` and `openfisca.org` (knowing that current `openfisca.org` style might change).

**Comment by benjello** [comment]
The main point is what do w want to achieve and how ?
Since the first site is outdated and we want lo lighten the maintenance and attract contributors, I am more in favor of the second option.

**Comment by cbenz** [comment]
@sandcha I would prefer to drop the existing website, build a small website for `fr.openfisca.org` very close to `openfisca.org`, cherry-picking only some content from the current `openfisca.fr`.

Indeed [`openfisca-web-site`](https://github.com/openfisca/openfisca-web-site) is quite complex and it is a Python application; it could be a static website.

**Comment by fpagnoux** [comment]
Great, we have a consensus on rebuilding a small website from scratch :)

**Comment by fpagnoux** [comment]
On the new `fr.openfisca.org`, I suggest we first mention :

- An introduction : OpenFisca France is the first and most complete country modelized in OpenFisca. It has many variables and parameters, can be used for many area of the legislation, etc.
- The partners/contributors of OpenFisca-France : IPP, Etalab, Incubateur,  @adrienpacifico 's university.
- The reuses of OpenFisca-France (mes-aides, embauche, ui, demonstrator, PNDS...)

@benjello @sandcha @Anna-Livia @cbenz what do you think ?

**Comment by Anna-Livia** [comment]
I think it's a great Idea. 

Should we add the api demonstrator ?
 We should not forget the links the API, legislation explorer , the general documentation.

**Comment by fpagnoux** [comment]
Yes, the api demonstrator may be listed as an example.

**Comment by fpagnoux** [comment]
We reached consensus, PR to come later ;)
