### ISSUE TITLE
Atelier pour choisir la technologie du nouveau site

### ISSUE THREAD

**Issue by maukoquiroga** [openfisca/openfisca-web-site#62]
Relates to openfisca/openfisca-france#824

L'idée est d'utiliser une technologie avec une bonne adoption, pour augmenter les chances d'avoir de contributions et que tous les modules qu'on utilise soient mises à jours facilement.

Une bonne idée est React + Redux.

**Comment by sandcha** [comment]
Bilan de l'atelier du 31 janvier : [Next.js](https://learnnextjs.com)
Ce choix est compatible avec React (donc legislation-explorer).
